### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by zeynepiskndr** [facebookresearch/vsc2022#11]
```
conda create --name vsc-vcsl -c pytorch -c nvidia -c conda-forge pytorch \
   torchvision scikit-learn numpy pandas matplotlib faiss-gpu tqdm\
   networkx loguru numba cython h5py pytorch-cuda=11.7
```
I created a conda env using the above line. and then I ran this line:
```
python -m vsc.baseline.inference\
     --accelerator cuda --processes 2\
     --torchscript_path ./sscd_disc_mixup.no_l2_norm.torchscript.pt\
     --output_file ./output/training_queries.npz\
     --dataset_path ./training_dataset/queries
```
and this is the error I get:
RuntimeError: Distributed package doesn't have NCCL built in
In the section I used to install conda above, NCCL should normally be built in, but it wasn't. To solve this, I also tried to install NCCL.
`conda install -c conda-forge nccl`
Is there any other solution?

**Comment by edpizzi** [comment]
Is this on a machine with an nvidia GPU? I think `pytorch-cuda=11.7` should select a version of pytorch with cuda and NCCL built in (see [1]), although I notice that the official pytorch docs now specify `-c nvidia` instead of `-c conda-forge`, so maybe something has changed since we tested these installation instructions.

Unfortunately, I no longer have access to the cluster I used to test the installation instructions, and the machines I have access to require unusual setup steps, which complicates testing this.

[1] https://discuss.pytorch.org/t/runtimeerror-distributed-package-doesnt-have-nccl-built-in/176744

**Comment by zeynepiskndr** [comment]
> Is this on a machine with an nvidia GPU? I think `pytorch-cuda=11.7` should select a version of pytorch with cuda and NCCL built in (see [1]), although I notice that the official pytorch docs now specify `-c nvidia` instead of `-c conda-forge`, so maybe something has changed since we tested these installation instructions.
> 
> Unfortunately, I no longer have access to the cluster I used to test the installation instructions, and the machines I have access to require unusual setup steps, which complicates testing this.
> 
> [1] https://discuss.pytorch.org/t/runtimeerror-distributed-package-doesnt-have-nccl-built-in/176744

yes on a machine with Nvidia GPU 
```
python -c "import torch; print(torch.version.cuda)"
11.7
```
```
pip show torch
Name: torch
Version: 1.13.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /opt/conda/lib/python3.10/site-packages
Requires: nvidia-cublas-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, typing-extensions
Required-by: torchvision
```

**Comment by edpizzi** [comment]
Adding `nccl` to the conda installation seems like a reasonable fix.

**Comment by edpizzi** [comment]
I may have misunderstood your report. Are you saying that adding `nccl` to the conda installation resolved your issue, or is it still unresolved?

I believe you have to match the cuda library version to the type of GPU you have. Do you have a working pytorch environment on your machine that has nccl? If so, what package versions is that using?

[1] suggests the following debugging steps. I may not have have the expertise to interpret them, but they may be useful anyway:
```
python -m torch.utils.collect_env
```
```
torch.cuda.nccl.is_available(torch.randn(1).cuda())
torch.cuda.nccl.version()
```

You may not need nccl to use the VSC codebase. It's just used for distributed inference. Even for distributed inference it's not needed fundamentally, our code just uses it because it was convenient to run inference within PT Lightning. Does inference work if you set `--processes 1`?

**Comment by edpizzi** [comment]
No response, marking as closed
